### ISSUE TITLE
allowDoctype not used for cache

### ISSUE THREAD

**Issue by arosenheinrich** [rometools/rome-fetcher#19]
I encountered the following problem using release 1.5.1: when trying to fetch a feed using Doctype I can not fetch it out of the box anymore because this is restricted by default. Setting system property rome.allowDoctype:true should enable it again. But this only seems to work when using a fetcher without cache:

		URL url = new URL("http://www.immobilienmanager.de/?id=640&type=100");
		//FeedFetcherCache feedInfoCache = HashMapFeedInfoCache.getInstance();
		//FeedFetcher feedFetcher = new HttpURLFeedFetcher(feedInfoCache);
		FeedFetcher feedFetcher = new HttpURLFeedFetcher();
		SyndFeed feed = feedFetcher.retrieveFeed(url);
		System.out.println(feed.getEntries().size());

When I use feedFetcher with feedInfoCache in my example it aint working. Seems like caches do not evaluate the rome.allowDoctype property.

**Comment by mishako** [comment]
Moved this issue to https://github.com/rometools/rome/issues/234 as part of https://github.com/rometools/rome/issues/217
