### ISSUE TITLE
Rome doesn't seem to parse the pubDate correctly out of the RSS feed when it is CDATA

### ISSUE THREAD

**Issue by PatrickGotthard** [rometools/rome-fetcher#2]
<pre>=== This issue was migrated from JIRA ===
Type: Bug
Priority: Minor
Status: Open
Resolution: Unresolved
Environment: Java 6/Linux/ Rome and Rome fetcher 1.0.
Reported by: Jeffrey Haskovec
Assigned to: Nick Lothian
Created: Fri Jan 13 22:30:47 CET 2012
Updated: Fri Oct 26 04:47:19 CEST 2012
JIRA Link: <a href="https://rometools.jira.com/browse/FETCHER-1">https://rometools.jira.com/browse/FETCHER-1</a>
=========================================</pre>
<p>Trying to read this feed:</p>

<p><a href="http://pmq.com/news/rss.php" class="external-link" rel="nofollow">http://pmq.com/news/rss.php</a></p>

<p>Here is an example of it:</p>

<p>&lt;?xml version="1.0" encoding="UTF-8"?&gt;<br/>
&lt;rss version="2.0"&gt;<br/>
&lt;channel&gt;<br/>
&lt;title&gt;PMQ News Room&lt;/title&gt;<br/>
&lt;description&gt;All the hottest pizza news.&lt;/description&gt;<br/>
&lt;link&gt;<a href="http://pmq.com/news" class="external-link" rel="nofollow">http://pmq.com/news</a>&lt;/link&gt;<br/>
&lt;language&gt;en-us&lt;/language&gt;<br/>
&lt;pubDate&gt;Fri, 13 Jan 2012 12:50:56 EST&lt;/pubDate&gt;<br/>
&lt;item&gt;<br/>
&lt;link&gt;<a href="http://pmq.com/news/news.php?id=15463" class="external-link" rel="nofollow">http://pmq.com/news/news.php?id=15463</a>&lt;/link&gt;<br/>
&lt;guid isPermaLink="true"&gt;<a href="http://pmq.com/news/news.php?id=15463" class="external-link" rel="nofollow">http://pmq.com/news/news.php?id=15463</a>&lt;/guid&gt;</p>

<p>&lt;title&gt;&lt;![CDATA<a href="https://rometools.jira.com/wiki/display/FETCHER/First+Mobile+Neapolitan+Pizzeria%2C+to+Launch+in+San+Francisco+in+February">First Mobile Neapolitan Pizzeria, to Launch in San Francisco in February</a>]&gt;&lt;/title&gt;<br/>
&lt;description&gt;&lt;![CDATA<span class="error">&#91;&quot;Ex-Flour + Water pizzaiolo Jon Darsky is launching a pioneering mobile operation called Del Popolo (&quot;of the people&quot;), as Tablehopper reports. Darsky and a design team have adapted a shipping container into a wood-fired pizzeria, loaded onto a flat-bed truck, with an on-board, 5,000-pound Stefano Ferrara pizza oven from Naples, just like the ones Una Pizza Napoletana and Cupola have,&quot; reports SanFrancisco.GrubStreet.com.&#93;</span>]&gt;&lt;/description&gt;<br/>
&lt;pubDate&gt;&lt;![CDATA<a href="https://rometools.jira.com/wiki/display/2012-01-12+11/18%3A03">2012-01-12 11:18:03</a>]&gt;&lt;/pubDate&gt;<br/>
&lt;comments&gt;<a href="http://pmq.com/news/news.php?id=15463" class="external-link" rel="nofollow">http://pmq.com/news/news.php?id=15463</a>&lt;/comments&gt;<br/>
&lt;/item&gt;<br/>
&lt;item&gt;<br/>
&lt;link&gt;<a href="http://pmq.com/news/news.php?id=15462" class="external-link" rel="nofollow">http://pmq.com/news/news.php?id=15462</a>&lt;/link&gt;<br/>
&lt;guid isPermaLink="true"&gt;<a href="http://pmq.com/news/news.php?id=15462" class="external-link" rel="nofollow">http://pmq.com/news/news.php?id=15462</a>&lt;/guid&gt;</p>

<p>&lt;title&gt;&lt;![CDATA<a href="https://rometools.jira.com/wiki/display/FETCHER/Pizza+Shop+Owner+Shocked+By+Food+Poisonings">Pizza Shop Owner Shocked By Food Poisonings</a>]&gt;&lt;/title&gt;<br/>
&lt;description&gt;&lt;![CDATA<span class="error">&#91;&quot;The owner of a Ballarat pizza shop closed down after a salmonella outbreak has pleaded to his customers for support as health authorities continued investigations into a regional egg supplier,&quot; reports SMH.com.au.&#93;</span>]&gt;&lt;/description&gt;<br/>
&lt;pubDate&gt;&lt;![CDATA<a href="https://rometools.jira.com/wiki/display/2012-01-12+10/46%3A22">2012-01-12 10:46:22</a>]&gt;&lt;/pubDate&gt;<br/>
&lt;comments&gt;<a href="http://pmq.com/news/news.php?id=15462" class="external-link" rel="nofollow">http://pmq.com/news/news.php?id=15462</a>&lt;/comments&gt;<br/>
&lt;/item&gt;</p>

<p>The pubdate is in CDATA and when I look at it in rome it is null.  So it isn't handled correctly, the title and description are being handled correctly in this case.</p>

**Comment by mishako** [comment]
Let's not mix up different date/time formats.
 * In the original ticket submitted by Jeffrey publish date is represented as `yyyy-MM-dd HH:mm:ss`. It doesn't match any existing format, so we shouldn't support it.
 * Patrick's example has `EEE, dd MMM yyyy HH:mm:ss z` with UTC time zone. It has been fixed in https://github.com/rometools/rome/pull/212.
 * Bob tries to parse feed with `EEE, dd MMM yyyy HH:mm:ss`, i.e. RFC 822 without a zone. It's not correct.

Looks like we can close this issue.

**Comment by mishako** [comment]
Closing this. Please speak up if you don't agree.
