### ISSUE TITLE
howto ignore ssl errors

### ISSUE THREAD

**Issue by pumpadump** [rometools/rome-fetcher#22]
Hi, 

I have a use case where i would like to retrieve a rss feed from sites that have invalid or broken certificates. Is there a possibility to configure the feedfetcher to ignore all ssl exceptions?

**Comment by PatrickGotthard** [comment]
Hi pumpadump,

could you please give us the Stacktrace and the URL of the feed?

Regards,
Patrick

**Comment by mishako** [comment]
Moved this issue to https://github.com/rometools/rome/issues/221 as part of https://github.com/rometools/rome/issues/217
