### ISSUE TITLE
RSS channel's pubDate and lastBuildDate are mixed.

### ISSUE THREAD

**Issue by PatrickGotthard** [rometools/rome-fetcher#4]
<pre>=== This issue was migrated from JIRA ===
Type: Bug
Priority: Major
Status: Open
Resolution: Unresolved
Environment: 1.0 version (of ROME Fetcher)
Reported by: Vlastimil Fürst
Assigned to: Nick Lothian
Created: Fri Jun 28 15:47:43 CEST 2013
Updated: Fri Jun 28 16:15:11 CEST 2013
JIRA Link: <a href="https://rometools.jira.com/browse/FETCHER-3">https://rometools.jira.com/browse/FETCHER-3</a>
=========================================</pre>
<p>In com.sun.syndication.feed.rss.Channel :<br/>
getLastBuildDate() always seem to return null;<br/>
getPubDate() returns pubDate correctly, but if pubDate tag isn't present in the RSS feed, content of lastBuildDate tag is returned instead.</p>

<p>This implies that in case both pubDate and lastBuildDate tags are filled, the contents of lastBuildDate can't be retrieved. In case only lastBuildDate is present, it can be read, but it's wrongly interpreted as pubDate.</p>

**Comment by mishako** [comment]
Moved this issue to https://github.com/rometools/rome/issues/226 as part of https://github.com/rometools/rome/issues/217
